name: TickChunks
description: 'Ensure that certain chunks keep receiving ticks when loaded; combine with keepchunks plugin! Usage: /tc ( k[eep] | r[elease] )'
main: uhl.mc.tickchunks.TickChunksPlugin
version: 1.0
load: POSTWORLD

softdepend: [keepchunks]

commands:
    tickchunks:
        aliases: [tc]
        description: "Adds or removes the chunk the player is currently in to/from the list of chunks to keep ticking. Usage: /tc ( k[eep] | r[elease] )"

permissions:
   tickchunks.*:
      children:
          tickchunks.keep: true
          tickchunks.release: true
   tickchunks.keep:
      default: op
   tickchunks.release:
      default: op
